export default {
	ADD_TASK: "ADD_TASK",
	DELETE_TASK: "DELETE_TASK",
	TOGGLE_COMPLETED_STATE_TASK: "TOGGLE_COMPLETED_STATE_TASK",
	FILTER_TASKS_BY: "FILTER_TASKS_BY",
	CLEAR_COMPLETED_TASKS: "CLEAR_COMPLETED_TASKS",
	REORDER_TASKS: "REORDER_TASKS",
	SET_ERROR: "SET_ERROR",
};
